# Description: Export wig files using MEDIPS.exportWIG() from the BAM files generated by step_1_fastq_to_bam.sh
# Author：Kui Chen → kui.chen@uhn.ca
# 1st Created: 2020-07-11
# Last Modified: 2023-12-20
# chromosome X and Y were excluded

library(MEDIPS)
library(edgeR)
library(BSgenome.Hsapiens.UCSC.hg19)

# Define the working directory and output directory
bamDir <- "/path/to/your/bam"  #path to the BAM_DIR generated by fastq_to_bam.sh
outdir <- "/path/to/your/wig"

# Check if the output directory exists, if not, create it
if (!dir.exists(outdir)) {
  dir.create(outdir, recursive = TRUE)
}

## Global parameters
BSgenome <- "BSgenome.Hsapiens.UCSC.hg19"
uniq <- 1e-3
extend <- 300
shift <- 0
ws <- 300
paired <- TRUE
chr.select <- paste0("chr",c(1:22,"M"))

## Generate wig from bam
BamsList <- list.files(path=bamDir, pattern="\\.bam$")
print(BamsList)

SetCreated.list <- list()
for(i in 1:length(BamsList)) {

SetCreated.list [[i]] <- MEDIPS.createSet(file= BamsList[[i]],BSgenome = BSgenome, extend = extend, shift = shift, uniq = uniq, window_size = ws, chr.select = chr.select, paired = paired)

}

names(SetCreated.list) <- BamsList

for(i in 1:length(SetCreated.list)) {
 MEDIPS.exportWIG(Set=SetCreated.list[[i]], file= paste0(BamsList[[i]],".wig"), format="count", descr= BamsList[[i]])
}

