##########################################################################################
# Runnning at H4H cluster with ≥ 180GB memory (veryhimem) configuration ##################
# Running time : ~2 hours for 240 samples ################################################
##########################################################################################


#!/bin/bash
#SBATCH -t 0-03:00:00
#SBATCH --mem=180G
#SBATCH -J wig_to_matrics
#SBATCH -p veryhimem
#SBATCH -c 2
#SBATCH -N 1
#SBATCH -o wig_to_matrics
#SBATCH --mail-type=ALL
#SBATCH --mail-user=username@uhn.ca

# Navigate to the directory containing the wig files generated by bam_to_wig.R
cd /path/to/your/wig
mkdir ../matrices

echo " wig to matrices converting initiated......"

# Generate matrics
for i in *.wig

do

j=$i$".txt"

awk 'FNR > 2 {
    split($0, newArray, " ")
    if (length(newArray) > 1) print "0"  >> "'$j'"
    else if (length(newArray) == 1) print $0 >> "'$j'"
}' $i

echo "0" >> $j

echo $i$" done"

mv *.txt ../matrices

# Optional: Remove the original wig files to save space
# echo "Removing wig files..."
# rm *.wig

done

